### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by CarlQLange**

### CODE REVIEW

**Comment by mikehenrty** [comment]
You know what's funny, I actually looked up the spelling of this word to make sure I had it right, and still got it wrong!

You know what else is funny Carl? You are the only person I know who uses the github feed to keep track of his friends.

You know what else is funny? I still have these:
msg130030785-112394

**Comment by CarlQLange** [comment]
I don't have twitter anymore, how am I supposed to keep tabs on people if not by snooping presentations they've written? Congratulations on the role at Dropbox by the way - and also all the other life events.

I have no recollection, at all, of what might be in those envelopes... I'm worried it's something really incriminating.

**Comment by mikehenrty** [comment]
>  I'm worried it's something really incriminating.

Your secret is safe with me!

**Comment by mikehenrty** [comment]
> Your secret is safe with me!

probably

**Pull request merged**
